platform :ios, '7.0'
pod 'AFNetworking', '~> 2.6.1'
pod 'MBProgressHUD', '~> 0.9.1'
pod 'MJExtension', '~> 3.0.7'
pod 'MJRefresh', '~> 3.1.0'
pod 'SDWebImage', '~> 3.7.3'
pod 'JSONModel', '~> 1.1.2'
pod 'YLGIFImage', '~> 0.11'
pod 'SVProgressHUD'
pod 'FMDB', '~> 2.6.2'
